apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: github
  #address: https://github.com/<username>/fleet-infra
  secretRef:
    name: github