apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/monitoring/stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system