apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: demo
spec:
  chart:
    spec:
      version: ">=0.1.0"
      valuesFiles:
        - values.yaml
        - staging-values.yaml
  test:
    enable: false
  values:
    image: "smana/helloworld:staging-cd2c525-1624897137" # {"$imagepolicy": "flux-system:helloworld"}
