apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: demo
spec:
  chart:
    spec:
      version: ">=0.1.0"
  test:
    enable: false
  values:
    global:
      environment: "staging"
      cluster: "staging"
      region: "eu-west-1"
    replicaCount: 2
    resources:
      limits:
        cpu: 100m
        memory: 198Mi
    image: "smana/helloworld:staging-947009c-1626164008" # {"$imagepolicy": "flux-system:helloworld"}
