apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base/helloworld
  - secrets.yaml
  - image-policy.yaml
patchesStrategicMerge:
  - helm-values.yaml
